name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your source branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Copy files to deploy
        run: |
          mkdir output
          cp templates/index.html output/index.html
          # Copy any other static files (CSS/JS/images) if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
